        <li class="backlog">
          <ul>
            <li class="title"><h3>Backlog</h3></li>
            <?php
            $html = file_get_contents('http://cvbacklog.gordon-oheim.biz/');
            $backlog = new DOMDocument();
            $backlog->loadHTML($html);
            $nodes = $backlog->getElementsByTagName('li');

            foreach ($nodes as $index => $node) {
            ?>
            <li class="cv"><a href="<?php echo $node->getElementsByTagName('a')->item(0)->getAttribute('href'); ?>"><?php echo $node->getElementsByTagName('a')->item(0)->getAttribute('class') . ': ' . htmlspecialchars($node->nodeValue, ENT_QUOTES, 'UTF-8'); ?></a></li>
            <?php if ($index === 5) break; } ?>
            <li class="more"><a href="http://cvbacklog.gordon-oheim.biz/" target="_blank">more</a></li>
          </ul>
        </li>