        <li class="contributors">
          <ul>
            <li class="title"><h3>Contributors</h3></li>
            <li><a href="https://github.com/DaveRandom" target="_blank">Chris Wright</a></li>
            <li><a href="https://github.com/hakre" target="_blank">Hakre</a></li>
            <li><a href="https://github.com/ktomk" target="_blank">ktomk</a></li>
            <li><a href="https://github.com/orourkek" target="_blank">orourkek</a></li>
            <li><a href="https://github.com/PeeHaa" target="_blank">Pieter Hordijk</a></li>
          </ul>
        </li>