<h1>Changelog</h1>
<dl>
  <dt><h2>0.20.0 <span>23-01-2013</span></h2></dt>
  <dd>
    <ul>
      <li>Removed jQuery dependency</li>
      <li>Removed dupes helper until it is improved in the next version</li>
      <li>Enable more features by default on install</li>
      <li>Implemented automatic delv to cv conversion for not yet closed questions</li>
      <li>Fixed bug where "middleclicks" weren't properly recognized</li>
      <li>Ported plugin to Firefox</li>
      <li>Implemented auto update feature</li>
    </ul>
  </dd>
  <dt><h2>0.19.0 <span>15-10-2012</span></h2></dt>
  <dd>
    <ul>
      <li>Implemented DOM mutation listeners instead of 1 second ticker</li>
      <li>Option for removal of avatar notifications for completed requests and requests that scroll off screen</li>
      <li>Option for removal of oneboxes for completed requests</li>
      <li>Option for strikethrough of completed requests</li>
    </ul>
  </dd>
  <dt><h2>0.18.1 <span>19-06-2012</span></h2></dt>
  <dd>
    <ul>
      <li>Fixed issue with default value for settings</li>
    </ul>
  </dd>
  <dt><h2>0.18.0 <span>12-06-2012</span></h2></dt>
  <dd>
    <ul>
      <li>Implemented dupes helper</li>
      <li>Fixed the backlog to display cv-pls vs delv-pls</li>
    </ul>
  </dd>
  <dt><h2>0.17.0 <span>07-06-2012</span></h2></dt>
  <dd>
    <ul>
      <li>Implemented feature to change the room description to cv backlog</li>
      <li>Implemented changelog</li>
      <li>Set default height of oneboxes to 30px</li>
    </ul>
  </dd>
</dl>