<h1>Downloads</h1>
<h2>Stable</h2>
<ul>
  <li><a href="/chrome/cv-pls_<?= STABLE_VERSION ?>.crx">Chrome <?= STABLE_VERSION ?></a></li>
  <li><a href="/mozilla/cv-pls_<?= STABLE_VERSION ?>.xpi">Firefox <?= STABLE_VERSION ?></a></li>
</ul>
<?php if (defined('DEVELOPMENT_VERSION')) { ?>
<h2>Beta</h2>
<ul>
  <li><a href="/chrome/cv-pls_<?= DEVELOPMENT_VERSION ?>.crx">Chrome <?= DEVELOPMENT_VERSION ?></a></li>
  <li><a href="/mozilla/cv-pls_<?= DEVELOPMENT_VERSION ?>.xpi">Firefox <?= DEVELOPMENT_VERSION ?></a></li>
</ul>
<?php } ?>