<h1>[cv-pls]</h1>
<p>This browser extension will help you close voting questions on Stack Overflow. It will convert all [cv-pls] and [delv-pls] requests into nice oneboxes in the SO chat.</p>
<p>This repository holds the core application code, in order to use it you will need to use one of the browser-specific wrappers. Currently the following wrappers are available:</p>

<table>
  <tr>
    <th>Browser</th>
    <th>Stable</th>
    <th>Beta</th>
  </tr>
  <tr>
    <td>
      <a href="https://github.com/cv-pls/chrome-cv-pls" target="_blank">Google Chrome</a>
    </td>
    <td>
      <a href="/chrome/cv-pls_<?= STABLE_VERSION ?>.crx"><?= STABLE_VERSION ?></a>
    </td>
    <td>
<?php if (defined('DEVELOPMENT_VERSION')) { ?>
      <a href="/chrome/cv-pls_<?= DEVELOPMENT_VERSION ?>.crx"><?= DEVELOPMENT_VERSION ?></a>
<?php } else { ?>
      <i>N/A</i>
<?php } ?>
    </td>
  </tr>
  <tr>
    <td>
      <a href="https://github.com/cv-pls/ff-cv-pls" target="_blank">Mozilla Firefox</a>
    </td>
    <td>
      <a href="/mozilla/cv-pls_<?= STABLE_VERSION ?>.xpi"><?= STABLE_VERSION ?></a>
    </td>
    <td>
<?php if (defined('DEVELOPMENT_VERSION')) { ?>
      <a href="/mozilla/cv-pls_<?= DEVELOPMENT_VERSION ?>.xpi"><?= DEVELOPMENT_VERSION ?></a>
<?php } else { ?>
      <i>N/A</i>
<?php } ?>
    </td>
  </tr>
</table>

<p>Please see the relevant project for browser-specific notes and installation instructions.</p>

<h2>Feature Overview</h2>
<ul>
  <li>Turn <code>[cv-pls]</code> and <code>[delv-pls]</code> requests into oneboxes</li>
  <li>Convenience buttons for creating <code>[cv-pls]</code> and <code>[delv-pls]</code> requests</li>
  <li>Various options for being notified of new requests, including @mention beep and avatar notifications</li>
  <li>Integration with the <a href="https://github.com/gooh/CVBacklog" target="_blank">CVBacklog</a></li>
  <li>Request progress indication in oneboxes and/or by striking through completed requests</li>
</ul>