<h1>Source</h1>
<p>The sourcecode of the plugins are freely available on <a href="https://github.com/cv-pls" target="_blank">GitHub</a>. The code is <a href="http://www.opensource.org/licenses/mit-license.html" target="_blank">MIT licensed</a>.</p>
<p>Currently there are three repositories for the plugins:</p>
<ul>
  <li><a href="https://github.com/cv-pls/cv-pls" target="_blank">cv-pls (which contains all the code shared by the different plugins)</a></li>
  <li><a href="https://github.com/cv-pls/chrome-cv-pls" target="_blank">chrome-cv-pls (which contains all the Chrome specific code)</a></li>
  <li><a href="https://github.com/cv-pls/ff-cv-pls" target="_blank">ff-cv-pls (which contains all the Firefox specific code)</a></li>
</ul>