        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/changelog">Changelog</a></li>
            <li><a href="/source">Source</a>
              <ul>
                <li><a href="https://github.com/cv-pls/cv-pls" target="_blank">Base</a></li>
                <li><a href="https://github.com/cv-pls/chrome-cv-pls" target="_blank">Chrome</a></li>
                <li><a href="https://github.com/cv-pls/ff-cv-pls target="_blank">Firefox</a></li>
              </ul>
            </li>
            <li><a href="/downloads">Downloads</a>
              <ul>
                <li><a href="">Chrome v0.20.0 (stable)</a></li>
                <li><a href="">Firefox v0.20.0 (stable)</a></li>
              </ul>
            </li>
            <li><a href="https://github.com/cv-pls/cv-pls/issues?state=open" target="_blank">Issuetracker</a></li>
          </ul>
        </nav>