        <?php $path = '/' . trim($_SERVER['REQUEST_URI'], '/'); ?>
        <nav>
          <ul>
            <li<?php if ($path == '/') echo ' class="active"'; ?>><a href="/">Home</a></li>
            <li<?php if ($path == '/changelog') echo ' class="active"'; ?>><a href="/changelog">Changelog</a></li>
            <li<?php if ($path == '/source') echo ' class="active"'; ?>><a href="/source">Source</a>
              <ul>
                <li><a href="https://github.com/cv-pls/cv-pls" target="_blank">Base</a></li>
                <li><a href="https://github.com/cv-pls/chrome-cv-pls" target="_blank">Chrome</a></li>
                <li><a href="https://github.com/cv-pls/ff-cv-pls" target="_blank">Firefox</a></li>
              </ul>
            </li>
            <li<?php if ($path == '/downloads') echo ' class="active"'; ?>><a href="/downloads">Downloads</a>
              <ul>
                <li><a href="/chrome/cv-pls_<?= STABLE_VERSION ?>.crx">Chrome v<?= STABLE_VERSION ?> (stable)</a></li>
                <li><a href="/mozilla/cv-pls_<?= STABLE_VERSION ?>.xpi">Firefox v<?= STABLE_VERSION ?> (stable)</a></li>
              </ul>
            </li>
            <li><a href="https://github.com/cv-pls/cv-pls/issues?state=open" target="_blank">Issuetracker</a></li>
          </ul>
        </nav>